POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "bbbbbbbb",
    "email": "bbbbbb",
    "age": 19
}

###

GET http://localhost:3003/user

###

POST http://localhost:3003/product
Content-Type: application/json

{
    "name": "produto1",
    "description": "produto legal",
    "price": 19
}


###

GET http://localhost:3003/product

###