###
PUT http://localhost:3003/user
Content-Type: application/json

 {
     "name": "fsdfsdgffsd",
     "nickname": "gfgfd",
     "email": "aaagfdgfgdf"
 }

###

###

GET http://localhost:3003/users/43

###

PUT http://localhost:3003/user/edit/43
Content-Type: application/json

{
"name": "OMG DEU BOM",
"nickname": "gfdgfd"
}

###





###

GET http://localhost:3003/

###